{% set name = "gmatelastic" %}
{% set version = "0.2.0" %}
{% set sha256 = "f3f3dae9e24392da489e0ac10f59a002507a06a3a5bacdd493c887a8f30a3fcb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastic/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - xtensor
  run:
    - xtensor

test:
  commands:
    - test -d ${PREFIX}/include/GMatElastic  # [unix]
    - test -f ${PREFIX}/include/GMatElastic/Cartesian3d.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/GMatElastic/GMatElasticConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\GMatElastic\Cartesian3d.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\GMatElasticConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/GMatElastic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Linear elastic material model (C++ header-only library).
  description: Linear elastic material model (C++ header-only library).
  doc_url: https://github.com/tdegeus/GMatElastic
  dev_url: https://github.com/tdegeus/GMatElastic

extra:
  recipe-maintainers:
    - tdegeus
